version: '3.3'
services:
    sync:
        container_name: btsync
        ports:
            - '127.0.0.1:8888:8888'
            - 55555
        volumes:
            - './sync:/mnt/sync'
        restart: on-failure
        image: resilio/sync