services:
  browser-use:
    image: vovan/browser-use
    container_name: browser-use
    environment:
      - OPENAI_API_KEY=${OPENAI_BROWSER_USE_KEY}
      - BROWSER_USE_LOGGING_LEVEL=debug
      - OLLAMA_BASE_URL=http://ollama:11434
      - KLUSTER_AI_BROWSER_USE=${KLUSTER_AI_BROWSER_USE}
    ports:
      - '5900:5900'
    depends_on:
      - ollama
