version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8707:8080"
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - BASE_URL=http://localhost:8707/
      - INSTANCE_NAME=searxng
      - SEARXNG_BASE_URL=http://localhost:8707/
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    restart: unless-stopped
