version: '3.7'

services:
  rhasspy:
    image: rhasspy/rhasspy
    container_name: rhasspy
    restart: unless-stopped
    ports:
      - "12101:12101"
    volumes:
      - $HOME/.config/rhasspy/profiles:/profiles
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/snd:/dev/snd
    command: >
      --user-profiles /profiles \
      --profile ru